name: Java CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Aciona o workflow em qualquer branch
  pull_request:
    branches:
      - '**'  # Aciona o workflow em qualquer pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
    
